mapboxgl.accessToken='pk.eyJ1IjoiZ2l2aW5ndHJlZSIsImEiOiJjbXA3MGdjczcwMXF1MnFwdjBzZ2lsdnc1In0.rphe-zIBwe1nLX-wKXXPgw';
const SC={energy:'#F59E0B',climate:'#10B981',agritech:'#84CC16','economic-inclusion':'#6366F1',infrastructure:'#8B5CF6',conservation:'#059669',fintech:'#3B82F6',housing:'#EC4899',health:'#EF4444','circular-economy':'#F97316',other:'#9CA3AF'};
const SL={energy:'Energy',climate:'Climate',agritech:'Agritech','economic-inclusion':'Economic Inclusion',infrastructure:'Infrastructure',conservation:'Conservation',fintech:'Fintech',housing:'Housing',health:'Health','circular-economy':'Circular Economy'};
const SIZE_RANGES=[{id:'under1m',label:'<$1M',min:0,max:1e6},{id:'1to10m',label:'$1-10M',min:1e6,max:1e7},{id:'10to50m',label:'$10-50M',min:1e7,max:5e7},{id:'50to250m',label:'$50-250M',min:5e7,max:2.5e8},{id:'over250m',label:'$250M+',min:2.5e8,max:Infinity},{id:'undisclosed',label:'Undisclosed',min:null,max:null}];
const TYPE_OPTIONS=['Investment','Fund Launch','Loan','Partnership','Grant'];
const SOURCE_OPTIONS=['VC/PE','DFI','Family Office','Foundation','Government','Corporate'];
const CITIES={"São Paulo":{coords:[-46.6333, -23.5505],state:"SP",blurb:"São Paulo is the financial capital of Latin America and the epicenter of Brazil's impact investing ecosystem.",sidebar:"Key hubs: Vox Capital, eB Capital, Fama Re.Capital, MOV Investimentos, Lightrock LatAm. Hosts Impacta Mais (1,200+ delegates)."},
"Rio de Janeiro":{coords:[-43.1729, -22.9068],state:"RJ",blurb:"Rio de Janeiro anchors Brazil's social finance and crowdlending innovation.",sidebar:"Sitawi Finance for Good (16 years), pioneering crowdlending with a 4.27% default rate."},
"Santos":{coords:[-46.3336, -23.9608],state:"SP",blurb:"Santos is Latin America's largest port. Global DFIs are investing in port modernization.",sidebar:"J.P. Morgan DFI financing new container terminal capacity for agricultural supply chains."},
"Brasília":{coords:[-47.8919, -15.7975],state:"DF",blurb:"Brazil's federal capital shapes national impact economy policy.",sidebar:"Eco Invest Brasil (IDB/FCDO) creates FX hedging mechanisms to mobilize private capital for climate."},
"New York City":{coords:[-74.006, 40.7128],state:"NY",blurb:"New York is the largest impact investing market in the US, with $40M+ in city-backed catalytic capital and dozens of diversity-focused VC firms.",sidebar:"Key players: NYCEDC Catalyst Fund, Harlem Capital, Open Opportunity Fund, Maycomb Capital. Hosts SOCAP satellite events and Climate Week NYC."},
"London":{coords:[-0.1276, 51.5074],state:"England",blurb:"London is positioning itself as the global capital of impact investing, with the UK market surpassing £11B in 2024 and new government-backed vehicles like the £500M Better Futures Fund.",sidebar:"Key players: Bridges Fund Management (£1.8B+ raised), Better Society Capital, Big Society Capital. Home to the Impact Investor Global Summit."},
"Singapore":{coords:[103.8198, 1.3521],state:"",blurb:"Singapore is the hub for impact investing across Asia, anchored by Temasek's ABC World framework and a growing ecosystem of pan-Asian impact PE funds.",sidebar:"Key players: ABC Impact (Temasek-backed, $600M+ Fund II), DBS, UOB. Centre for Impact Investing and Practices. MAS green finance initiatives."},
"Accra":{coords:[-0.187, 5.6037],state:"Greater Accra",blurb:"Accra is West Africa's emerging impact investing hub, home to the Ci-Gaba Fund-of-Funds and the annual Africa Impact Summit drawing 500+ delegates from 20+ countries.",sidebar:"Key players: Impact Investing Ghana (IIGh), Savanna Impact Advisory, FSD Africa. Government launched Climate Financing Division and Green/Social Bond Framework."},
"Sydney":{coords:[151.2093, -33.8688],state:"NSW",blurb:"Sydney anchors Australia's rapidly growing impact investing market, with AUD 9B in clean energy commitments in 2024 and the government-backed Clean Energy Finance Corporation deploying record capital.",sidebar:"Key players: CEFC ($32.5B allocation), Australian Impact Investments, NorthStar Impact Funds. Hosts the annual Impact Investment Summit at ICC Sydney."},
"Tokyo":{coords:[139.6917, 35.6895],state:"",blurb:"Tokyo is the center of Japan's growing impact investing ecosystem, backed by government-private sector partnerships and JICA's expanding global impact portfolio. Japan's National Advisory Board (GSG member) is driving policy alignment.",sidebar:"Key players: SIIF (Social Innovation & Investment Foundation), JICA, Shinsei Impact, GSG Impact Japan. Themes: aging society solutions, financial inclusion across Asia, clean energy transition."}};
const COUNTRY_DATA={"Brazil":{coords:[-51.9, -14.2],labelCoords:[-51.9, -8.5],blurb:"Brazil is Latin America's largest impact investing market and the sixth-largest economy globally. The ecosystem spans over a dozen dedicated fund managers, government-backed programs, and a national advisory board.",sidebar:"Key cities: São Paulo (financial hub), Rio (social finance), Brasília (policy), Santos (trade). Themes: climate, energy transition, economic inclusion, regenerative agriculture, conservation.",zoomTo:{"center": [-49.5, -16], "zoom": 4.2}},
"United States":{coords:[-95.7, 37.1],labelCoords:[-98, 39.5],blurb:"The US is the world's largest impact investing market, with over $1 trillion in assets under management. New York City alone has deployed $65M+ through city-backed impact funds targeting diverse entrepreneurship.",sidebar:"Key hubs: NYC (Catalyst Fund, Harlem Capital), San Francisco (SOCAP), Boston (impact PE). Themes: economic inclusion, diverse founders, climate tech, community development.",zoomTo:{"center": [-95.7, 38], "zoom": 4}},
"United Kingdom":{coords:[-1.5, 52.5],labelCoords:[-2.5, 54],blurb:"The UK impact investing market topped £11B in 2024, growing 10% annually. London is home to pioneering firms like Bridges Fund Management and government-backed institutions channeling capital into social outcomes.",sidebar:"Key players: Bridges FM (£1.8B+), Better Society Capital, Big Society Capital. Policy: £500M Better Futures Fund, Office for the Impact Economy. Themes: social housing, inclusive growth, climate.",zoomTo:{"center": [-2, 54], "zoom": 5.5}},
"Singapore":{coords:[103.8, 1.35],labelCoords:[103.8, 1.35],blurb:"Singapore punches above its weight in impact investing, anchored by Temasek's multi-billion-dollar commitment through ABC Impact and supported by MAS green finance initiatives and a growing ecosystem of pan-Asian impact funds.",sidebar:"Key players: ABC Impact ($600M+ Fund II), Temasek Trust, DBS, UOB. Themes: climate/water solutions, sustainable food, healthcare, financial/digital inclusion across Asia.",zoomTo:{"center": [103.8, 1.35], "zoom": 11}},
"Ghana":{coords:[-1.0, 7.9],labelCoords:[-1.2, 7.5],blurb:"Ghana is pioneering domestic capital mobilization for impact in West Africa. The Ci-Gaba Fund-of-Funds is the region's first domestically domiciled private fund of funds, unlocking pension capital for SMEs across Ghana, Nigeria, Senegal, and Côte d'Ivoire.",sidebar:"Key players: Impact Investing Ghana (GSG National Partner), Savanna Impact Advisory, FSD Africa. Themes: SME finance, pension capital mobilization, blended finance, gender lens investing.",zoomTo:{"center": [-1.5, 7.5], "zoom": 7}},
"Australia":{coords:[134, -25.3],labelCoords:[134, -25],blurb:"Australia's impact investing market is accelerating, with AUD 9B in clean energy commitments in 2024 and the government-backed CEFC deploying record AUD 4.7B in a single year. The market spans renewable energy, social housing, and First Nations investment.",sidebar:"Key players: CEFC ($32.5B allocation), Australian Impact Investments, Infradebt, Impact Investing Australia. Themes: renewables, social/affordable housing, First Nations, energy transition.",zoomTo:{"center": [134, -25], "zoom": 4.5}},
"Japan":{coords:[138.2, 36.2],labelCoords:[138.2, 37.5],blurb:"Japan's impact investing market has grown rapidly since the government's 2014 social impact commitment, with JICA emerging as a major global DFI deploying capital across Asia and Africa. The Social Innovation and Investment Foundation anchors the domestic ecosystem.",sidebar:"Key players: SIIF, JICA ($40M+ impact allocations), Shinsei Impact, GSG Impact Japan (NAB). Policy: Tokyo Metropolitan Government public-private impact growth fund. Themes: aging society, financial inclusion, clean energy.",zoomTo:{"center": [138, 37], "zoom": 5.5}}};
const deals=[
{investor:"I Squared Capital",recipient:"Órigo Energia",dealType:"Investment",amount:400000000.0,sector:"energy",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"Jan 2024",year:2024,source:"Reuters",notes:"49% stake in Brazil's largest distributed solar generation platform."},
{investor:"Augment Infrastructure",recipient:"Órigo Energia",dealType:"Investment",amount:140000000.0,sector:"energy",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2022",year:2022,source:"Órigo Energia IR",notes:"BRL 700M in renewable energy infrastructure investment."},
{investor:"eB Capital",recipient:"Bioo",dealType:"Investment",amount:50000000.0,sector:"climate",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2023",year:2023,source:"ImpactAlpha",notes:"Animal protein waste → biomethane. Energy transition fund."},
{investor:"Vox Capital / TNC / Moore Fdn",recipient:"Amazon NBS Fund",dealType:"Fund Launch",amount:250000000.0,sector:"conservation",sourceType:"Foundation",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"ImpactAlpha",notes:"Catalytic capital for blended finance around the Amazon."},
{investor:"Wright Capital",recipient:"NBS/Regen Ag/Climate FoF",dealType:"Fund Launch",amount:35000000.0,sector:"climate",sourceType:"Family Office",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"ImpactAlpha",notes:"Manages wealth of 40+ Brazilian families."},
{investor:"Fama Re.Capital",recipient:"LatAm Climate Turnaround Fund",dealType:"Fund Launch",amount:null,sector:"climate",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2023",year:2023,source:"ImpactAlpha",notes:"Invests in high-emitting companies to push decarbonization."},
{investor:"Fama Re.Capital",recipient:"Gaia Socio-Bioeconomy Fund",dealType:"Fund Launch",amount:null,sector:"agritech",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2024",year:2024,source:"ImpactAlpha",notes:"Affordable loans to small regenerative agriculture businesses."},
{investor:"InMotion Ventures (JLR)",recipient:"Energy Source",dealType:"Investment",amount:1200000.0,sector:"circular-economy",sourceType:"Corporate",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"Feb 2024",year:2024,source:"TechFundingNews",notes:"Lithium battery recycling. InMotion's first Brazil investment."},
{investor:"Estímulo",recipient:"3,400+ SMEs",dealType:"Loan",amount:40000000.0,sector:"economic-inclusion",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2024",year:2024,source:"ImpactAlpha / HBS",notes:"Blended finance credit fund for low-income regions."},
{investor:"Traive / Instituto Folio",recipient:"GAN Fund",dealType:"Fund Launch",amount:50000000.0,sector:"agritech",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"Climate Policy Initiative",notes:"Hybrid FIDC/CRA for bioinputs in regenerative agriculture."},
{investor:"BNDES",recipient:"Eve Air Mobility (Embraer)",dealType:"Loan",amount:40000000.0,sector:"infrastructure",sourceType:"DFI",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"BayBrazil",notes:"R$200M for eVTOL aircraft R&D and certification."},
{investor:"Crescera Capital",recipient:"Colmeia",dealType:"Investment",amount:3600000.0,sector:"housing",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"BayBrazil",notes:"R$18M for sustainable construction solutions."},
{investor:"Co-Capital / Din4mo / Oogway",recipient:"Mútua",dealType:"Investment",amount:null,sector:"fintech",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"ImpactAlpha",notes:"AI-powered impact data mapping platform. SDG/IRIS+ metrics."},
{investor:"Lightrock",recipient:"Portfolio (12+ ventures)",dealType:"Investment",amount:700000000.0,sector:"economic-inclusion",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2024",year:2024,source:"ImpactAlpha",notes:"$700M deployed across LatAm. Backed by Liechtenstein royal family."},
{investor:"Sitawi Finance for Good",recipient:"Na'kau (+ portfolio)",dealType:"Loan",amount:null,sector:"economic-inclusion",sourceType:"DFI",city:"Rio de Janeiro",state:"RJ",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"Devex",notes:"Crowdlending platform. 'Empathetic capital' model. 4.27% default rate."},
{investor:"J.P. Morgan DFI",recipient:"DP World (container terminal)",dealType:"Investment",amount:null,sector:"infrastructure",sourceType:"DFI",city:"Santos",state:"SP",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"Devex",notes:"12.5M metric tons grain/fertilizer capacity. $2.5T sustainable dev push."},
{investor:"Eco Invest Brasil (Gov/IDB/FCDO)",recipient:"Climate projects (program)",dealType:"Partnership",amount:null,sector:"climate",sourceType:"DFI",city:"Brasília",state:"DF",country:"Brazil",continent:"South America",date:"2024",year:2024,source:"OECD / ImpactAlpha",notes:"FX hedging program. Private banks bid for public climate funding."},
{investor:"Eqwow Ventures",recipient:"Healthcare/Fintech/Energy",dealType:"Fund Launch",amount:null,sector:"health",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"ImpactAlpha",notes:"LatAm talent, asset light, regional expansion thesis."},
{investor:"Potencia Ventures (Kelly Michel)",recipient:"50+ impact funds incl. Vox, Artemisia",dealType:"Investment",amount:null,sector:"economic-inclusion",sourceType:"Foundation",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2002-present",year:2024,source:"ImpactAlpha",notes:"Portland-based endowment. Ecosystem catalyst. 30+ direct investments."},
{investor:"XP Asset Management (Infra V)",recipient:"Eveo",dealType:"Investment",amount:20000000.0,sector:"infrastructure",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"BayBrazil",notes:"R$100M for private cloud and data center. 31.85% stake."},
{investor:"Meraki Impact",recipient:"Smallholder finance (Brazil)",dealType:"Investment",amount:null,sector:"agritech",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2024",year:2024,source:"ImpactAlpha / Toniic",notes:"Catalytic capital. Closing capital gap for smallholder finance."},
{investor:"Maya Capital",recipient:"Portfolio (Brazil VC)",dealType:"Fund Launch",amount:null,sector:"fintech",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"ImpactAlpha",notes:"LatAm-focused fund actively raising capital."},
{investor:"Vox Capital",recipient:"Tech for Good Growth II",dealType:"Fund Launch",amount:null,sector:"economic-inclusion",sourceType:"VC/PE",city:"São Paulo",state:"SP",country:"Brazil",continent:"South America",date:"2025",year:2025,source:"Vox Capital",notes:"Currently raising. 7th VC fund. Seed-stage focus."},
{investor:"NYCEDC",recipient:"NYC Catalyst Fund II (11+ fund managers)",dealType:"Fund Launch",amount:25000000.0,sector:"economic-inclusion",sourceType:"Government",city:"New York City",state:"NY",country:"United States",continent:"North America",date:"2025",year:2025,source:"NYCEDC",notes:"Impact investing vehicle for diverse entrepreneurship and economic mobility. Expected to catalyze $125M+."},
{investor:"Harlem Capital",recipient:"Diverse founders (75+ portfolio cos)",dealType:"Fund Launch",amount:150000000.0,sector:"economic-inclusion",sourceType:"VC/PE",city:"New York City",state:"NY",country:"United States",continent:"North America",date:"2024",year:2024,source:"NYCEDC / Harlem Capital",notes:"Diversity-focused VC. Mission: invest in 1,000 diverse founders over 20 years."},
{investor:"Bridges Fund Management",recipient:"Inclusive Growth Fund (UK social enterprises)",dealType:"Fund Launch",amount:82000000.0,sector:"economic-inclusion",sourceType:"VC/PE",city:"London",state:"England",country:"United Kingdom",continent:"Europe",date:"2024",year:2024,source:"Impact Investor",notes:"£65M seeded from Bridges Evergreen. Purpose-driven businesses for vulnerable groups."},
{investor:"Bridges Fund Management",recipient:"Alina Homecare",dealType:"Investment",amount:null,sector:"health",sourceType:"VC/PE",city:"London",state:"England",country:"United Kingdom",continent:"Europe",date:"2025",year:2025,source:"Bridges FM",notes:"UK home care for vulnerable elderly. Part of Bridges' Inclusive Growth strategy."},
{investor:"ABC Impact (Temasek-backed)",recipient:"Fund II (pan-Asia impact PE)",dealType:"Fund Launch",amount:600000000.0,sector:"climate",sourceType:"VC/PE",city:"Singapore",state:"",country:"Singapore",continent:"Asia",date:"2025",year:2025,source:"PR Newswire",notes:"Doubled Fund I. LPs: Temasek, ADB, Mapletree. Climate, food, healthcare, financial inclusion."},
{investor:"ABC Impact / DBS / UOB",recipient:"Sustainability-linked subscription facility",dealType:"Loan",amount:110000000.0,sector:"climate",sourceType:"VC/PE",city:"Singapore",state:"",country:"Singapore",continent:"Asia",date:"2025",year:2025,source:"ANTARA / PRNewswire",notes:"Converted conventional loan to sustainability-linked instrument. GHG reduction targets."},
{investor:"Ci-Gaba Fund-of-Funds (IIGh/Savanna)",recipient:"West African venture funds + SMEs",dealType:"Fund Launch",amount:75000000.0,sector:"economic-inclusion",sourceType:"DFI",city:"Accra",state:"Greater Accra",country:"Ghana",continent:"Africa",date:"2023",year:2023,source:"FSD Africa / GNA",notes:"$75M target. Blended finance unlocking pension capital for West African SMEs."},
{investor:"FSDAi (FSD Africa Investments)",recipient:"Ci-Gaba Fund",dealType:"Investment",amount:7500000.0,sector:"economic-inclusion",sourceType:"DFI",city:"Accra",state:"Greater Accra",country:"Ghana",continent:"Africa",date:"2026",year:2026,source:"FSD Africa",notes:"UK-backed specialist investor anchoring Ci-Gaba first close. 25,000 jobs target."},
{investor:"Clean Energy Finance Corp (CEFC)",recipient:"Renewable energy + grid infrastructure",dealType:"Investment",amount:3100000000.0,sector:"energy",sourceType:"Government",city:"Sydney",state:"NSW",country:"Australia",continent:"Oceania",date:"2025",year:2025,source:"Chambers & Partners",notes:"Australian government green bank. Record AUD 4.7B annual commitment. Rewiring the Nation."},
{investor:"Australian Impact Investments (Aii)",recipient:"Infradebt Ethical Fund + Ngutu College",dealType:"Investment",amount:16000000.0,sector:"infrastructure",sourceType:"VC/PE",city:"Sydney",state:"NSW",country:"Australia",continent:"Oceania",date:"2024",year:2024,source:"ImpactAlpha",notes:"Renewable energy/social infrastructure debt. First Nations college (50% Indigenous enrollment)."},
{investor:"Tokyo Metropolitan Government",recipient:"Public-Private Partnership Impact Growth Fund",dealType:"Fund Launch",amount:null,sector:"economic-inclusion",sourceType:"Government",city:"Tokyo",state:"",country:"Japan",continent:"Asia",date:"May 2024",year:2024,source:"SIIF / GSG Impact Japan",notes:"Government-backed fund promoting impact investment through public-private partnerships."},
{investor:"JICA",recipient:"Aavishkaar",dealType:"Investment",amount:40000000.0,sector:"economic-inclusion",sourceType:"DFI",city:"Tokyo",state:"",country:"Japan",continent:"Asia",date:"2025",year:2025,source:"ImpactAlpha",notes:"$40M investment in India/South Asia-focused impact fund manager. Financial inclusion and livelihoods."}
];

function fmt(a){if(!a)return'Undisclosed';if(a>=1e9)return'$'+(a/1e9).toFixed(1)+'B';if(a>=1e6)return'$'+(a/1e6).toFixed(0)+'M';if(a>=1e3)return'$'+(a/1e3).toFixed(0)+'K';return'$'+a}
function fmtUSD(a){if(!a)return'Undisclosed';if(a>=1e9)return'$'+(a/1e9).toFixed(1)+'B USD';if(a>=1e6)return'$'+(a/1e6).toFixed(0)+'M USD';return fmt(a)}
function isMobile(){return window.innerWidth<=640}
function jitter(b,i,s){const a=(i*137.508)*(Math.PI/180);const r=s*Math.sqrt(i+1);return[b[0]+r*Math.cos(a),b[1]+r*Math.sin(a)]}
const cityGroups={};deals.forEach(d=>{if(!cityGroups[d.city])cityGroups[d.city]=[];cityGroups[d.city].push(d)});
const filters={sector:new Set(),year:new Set(),type:new Set(),size:new Set(),source:new Set(),geo:new Set()};
let openCategory='sector',geoOpenContinent=null,geoHoverContinent=null,isolatedCountry=null,isoRadioTimer=null,lastFilters=null,undoTimer=null,lastCountry='Brazil',continentUndo={},fadingIsoCountry=null,fadingIsoTimer=null;
function totalActive(){let c=0;Object.values(filters).forEach(s=>c+=s.size);return c}
function matchFilter(d){if(filters.sector.size>0&&!filters.sector.has(d.sector))return false;if(filters.year.size>0&&!filters.year.has(String(d.year)))return false;if(filters.type.size>0&&!filters.type.has(d.dealType))return false;if(filters.source.size>0&&!filters.source.has(d.sourceType))return false;if(filters.geo.size>0&&!filters.geo.has(d.country))return false;if(isolatedCountry&&d.country!==isolatedCountry)return false;if(filters.size.size>0){let m=false;filters.size.forEach(sid=>{const r=SIZE_RANGES.find(x=>x.id===sid);if(!r)return;if(r.min===null){if(d.amount===null)m=true}else if(d.amount!==null&&d.amount>=r.min&&d.amount<r.max)m=true});if(!m)return false}return true}
function getFiltered(){return deals.filter(matchFilter)}
function saveFiltersSnapshot(){const snap={};Object.entries(filters).forEach(([k,s])=>snap[k]=new Set(s));snap._isolated=isolatedCountry;return snap}
function restoreFiltersSnapshot(snap){if(!snap)return;Object.entries(snap).forEach(([k,s])=>{if(k==='_isolated'){isolatedCountry=s}else{filters[k]=new Set(s)}})}
function clearAll(){lastFilters=saveFiltersSnapshot();Object.values(filters).forEach(s=>s.clear());isolatedCountry=null;fadingIsoCountry=null;if(fadingIsoTimer)clearTimeout(fadingIsoTimer)}
function getCountriesByContinent(){const m={};deals.forEach(d=>{if(!m[d.continent])m[d.continent]=new Set();m[d.continent].add(d.country)});const r={};Object.keys(m).sort().forEach(c=>{r[c]=[...m[c]].sort()});return r}
function getSuggestedCountries(){if(typeof map==='undefined'||!map.loaded())return[];const bounds=map.getBounds();const center=map.getCenter();const inView=new Set();const countryCoords={};deals.forEach(d=>{const c=CITIES[d.city];if(c&&bounds.contains(c.coords)){inView.add(d.country);if(!countryCoords[d.country])countryCoords[d.country]=COUNTRY_DATA[d.country]?COUNTRY_DATA[d.country].coords:c.coords}});return[...inView].sort((a,b)=>{const ca=countryCoords[a]||[0,0],cb=countryCoords[b]||[0,0];const da=Math.pow(ca[0]-center.lng,2)+Math.pow(ca[1]-center.lat,2);const db=Math.pow(cb[0]-center.lng,2)+Math.pow(cb[1]-center.lat,2);return da-db})}
function buildCluster(dl){const g={};dl.forEach(d=>{if(!g[d.city])g[d.city]=[];g[d.city].push(d)});return{type:'FeatureCollection',features:Object.entries(g).map(([c,cd])=>{const m=CITIES[c]||{coords:[-46.6333,-23.5505],state:''};const tc=cd.reduce((s,d)=>s+(d.amount||0),0);const sc=new Set(cd.map(d=>d.sector));const p={city:c,state:m.state,dealCount:cd.length,totalCapital:tc,totalCapitalFormatted:fmt(tc),sectorCount:sc.size,isCluster:cd.length>1};if(cd.length===1){const d=cd[0];Object.assign(p,{investor:d.investor,recipient:d.recipient,dealType:d.dealType,amount:d.amount,amountFormatted:fmt(d.amount),sector:d.sector,sectorLabel:SL[d.sector],color:SC[d.sector],date:d.date,source:d.source,notes:d.notes,country:d.country})}return{type:'Feature',geometry:{type:'Point',coordinates:m.coords},properties:p}})}}
function buildPins(dl){const g={};dl.forEach(d=>{if(!g[d.city])g[d.city]=[];g[d.city].push(d)});const f=[];Object.entries(g).forEach(([c,cd])=>{const m=CITIES[c]||{coords:[-46.6333,-23.5505]};cd.forEach((d,i)=>{const co=cd.length>1?jitter(m.coords,i,0.012):m.coords;f.push({type:'Feature',geometry:{type:'Point',coordinates:co},properties:{city:d.city,state:d.state,country:d.country,investor:d.investor,recipient:d.recipient,dealType:d.dealType,amount:d.amount,amountFormatted:fmt(d.amount),sector:d.sector,sectorLabel:SL[d.sector]||d.sector,color:SC[d.sector]||SC.other,date:d.date,source:d.source,notes:d.notes,radius:d.amount?Math.max(7,Math.min(18,5+Math.log10(d.amount)*1.8)):7}})})});return{type:'FeatureCollection',features:f}}
const catDefs=[{id:'sector',label:'Sector'},{id:'year',label:'Year'},{id:'type',label:'Type'},{id:'size',label:'Size'},{id:'source',label:'Source'},{id:'geo',label:'Geo'}];
function getOpts(cat){switch(cat){case'sector':return[...new Set(deals.map(d=>d.sector))].sort().map(s=>({id:s,label:SL[s]||s}));case'year':return[...new Set(deals.map(d=>String(d.year)))].sort().map(y=>({id:y,label:y}));case'type':return TYPE_OPTIONS.filter(t=>deals.some(d=>d.dealType===t)).map(t=>({id:t,label:t}));case'size':return SIZE_RANGES.filter(r=>{if(r.min===null)return deals.some(d=>d.amount===null);return deals.some(d=>d.amount!==null&&d.amount>=r.min&&d.amount<r.max)}).map(r=>({id:r.id,label:r.label}));case'source':return SOURCE_OPTIONS.filter(s=>deals.some(d=>d.sourceType===s)).map(s=>({id:s,label:s}));default:return[]}}
const topRowEl=document.getElementById('filterTopRow'),filterOptionsEl=document.getElementById('filterOptions');
function buildDesktop(){
topRowEl.innerHTML='';
catDefs.forEach(cat=>{const t=document.createElement('button');t.className='cat-tab'+(openCategory===cat.id?' open':'')+(filters[cat.id].size>0?' has-selection':'');t.innerHTML=cat.label+(filters[cat.id].size>0?`<span class="cat-count">${filters[cat.id].size}</span>`:'');t.addEventListener('click',()=>{openCategory=openCategory===cat.id?null:cat.id;buildDesktop()});topRowEl.appendChild(t)});
const clr=document.createElement('button');clr.className='desktop-clear-all'+(totalActive()>0?' visible':'');clr.textContent=lastFilters&&totalActive()===0?'Reapply last filters':'Clear all';clr.addEventListener('click',()=>{if(lastFilters&&totalActive()===0){restoreFiltersSnapshot(lastFilters);lastFilters=null;applyRebuild()}else{clearAll();applyRebuild()}});topRowEl.appendChild(clr);
filterOptionsEl.innerHTML='';if(!openCategory){filterOptionsEl.classList.remove('visible');return}filterOptionsEl.classList.add('visible');
if(openCategory==='geo'){buildGeoDesktop();return}
const row=document.createElement('div');row.className='filter-opts-row';
getOpts(openCategory).forEach(opt=>{const b=document.createElement('button');b.className='opt-btn'+(filters[openCategory].has(opt.id)?' active':'');if(openCategory==='sector'&&SC[opt.id])b.innerHTML=`<span class="opt-dot" style="background:${SC[opt.id]}"></span>${opt.label}`;else b.textContent=opt.label;b.addEventListener('click',()=>{if(filters[openCategory].has(opt.id))filters[openCategory].delete(opt.id);else filters[openCategory].add(opt.id);applyRebuild()});row.appendChild(b)});
if(filters[openCategory].size>0){const cc=document.createElement('button');cc.className='cat-clear visible';cc.textContent='Clear';cc.addEventListener('click',()=>{filters[openCategory].clear();applyRebuild()});row.appendChild(cc)}
filterOptionsEl.appendChild(row)}
function buildGeoDesktop(){
const line1=document.createElement('div');line1.className='filter-opts-row';line1.style.alignItems='center';
if(filters.geo.size>0||isolatedCountry){const gc=document.createElement('button');gc.className='cat-clear visible';gc.textContent='Clear';gc.addEventListener('click',()=>{filters.geo.clear();isolatedCountry=null;fadingIsoCountry=null;if(fadingIsoTimer)clearTimeout(fadingIsoTimer);applyRebuild()});line1.appendChild(gc)}
if(isolatedCountry){const ip=document.createElement('span');ip.className='geo-inview-pill isolated';ip.style.marginLeft='6px';ip.style.display='inline-flex';ip.style.alignItems='center';
const txt=document.createElement('span');txt.textContent=isolatedCountry;ip.appendChild(txt);
const rd=document.createElement('span');rd.className='pill-radio active';ip.appendChild(rd);
ip.addEventListener('click',()=>{fadingIsoCountry=isolatedCountry;isolatedCountry=null;if(isoRadioTimer)clearTimeout(isoRadioTimer);if(fadingIsoTimer)clearTimeout(fadingIsoTimer);fadingIsoTimer=setTimeout(()=>{fadingIsoCountry=null;buildDesktop()},10000);applyRebuild()});line1.appendChild(ip)}
if(!isolatedCountry&&fadingIsoCountry){const fp=document.createElement('span');fp.className='geo-inview-pill'+(filters.geo.has(fadingIsoCountry)?' selected':'');fp.style.marginLeft='6px';fp.style.display='inline-flex';fp.style.alignItems='center';
const txt=document.createElement('span');txt.textContent=fadingIsoCountry;fp.appendChild(txt);
const rd=document.createElement('span');rd.className='pill-radio fading';fp.appendChild(rd);
setTimeout(()=>{rd.classList.add('fade-out')},8000);
fp.addEventListener('click',()=>{if(filters.geo.has(fadingIsoCountry))filters.geo.delete(fadingIsoCountry);else filters.geo.add(fadingIsoCountry);applyRebuild()});line1.appendChild(fp)}
const excludeFromInview=new Set();if(isolatedCountry)excludeFromInview.add(isolatedCountry);if(fadingIsoCountry)excludeFromInview.add(fadingIsoCountry);
const suggested=getSuggestedCountries().filter(c=>!excludeFromInview.has(c));const maxShow=8-excludeFromInview.size;const visible=suggested.slice(0,Math.max(0,maxShow));const extra=suggested.length-visible.length;
visible.forEach(c=>{const pill=document.createElement('span');pill.className='geo-inview-pill'+(filters.geo.has(c)?' selected':'')+(isolatedCountry?' grayed':'');pill.textContent=c;pill.style.marginLeft='6px';pill.addEventListener('click',()=>{if(filters.geo.has(c))filters.geo.delete(c);else filters.geo.add(c);applyRebuild()});line1.appendChild(pill)});
if(extra>0){const more=document.createElement('span');more.className='geo-more-btn';more.textContent=`+${extra} more`;more.style.marginLeft='6px';more.style.position='relative';more.addEventListener('click',(ev)=>{ev.stopPropagation();let tip=more.querySelector('.geo-more-tip');if(tip){tip.style.display=tip.style.display==='none'?'block':'none'}else{tip=document.createElement('div');tip.className='geo-more-tip';tip.textContent='Click country names on the map or use the continent tabs to filter by country.';tip.style.display='block';tip.style.top='24px';tip.style.left='0';more.appendChild(tip);document.addEventListener('click',()=>{tip.style.display='none'},{once:true})}});line1.appendChild(more)}
filterOptionsEl.appendChild(line1);
{const cbc=getCountriesByContinent();const contNames=Object.keys(cbc);
const wrap=document.createElement('div');wrap.className='geo-tabbar-wrap';
const bar=document.createElement('div');bar.className='geo-tabbar';
let hoverTimer=null;
contNames.forEach(cont=>{const countries=cbc[cont];const tab=document.createElement('div');tab.className='geo-tab'+(geoOpenContinent===cont?' active':'');
const nm=document.createElement('span');nm.textContent=cont;tab.appendChild(nm);
const selCount=countries.filter(c=>filters.geo.has(c)).length;
const badge=document.createElement('span');badge.className='geo-tab-badge'+(selCount>0?'':' empty');
if(countries.every(c=>filters.geo.has(c))){badge.textContent='All'}else if(selCount>0){badge.textContent=selCount}else{badge.textContent='0'}
tab.appendChild(badge);
tab.addEventListener('click',(ev)=>{ev.stopPropagation();geoOpenContinent=geoOpenContinent===cont?null:cont;geoHoverContinent=null;buildDesktop()});
tab.addEventListener('mouseenter',()=>{if(hoverTimer)clearTimeout(hoverTimer);if(!geoOpenContinent)geoHoverContinent=cont;buildTabDropdown(wrap,cbc,geoOpenContinent||geoHoverContinent,!!geoOpenContinent)});
tab.addEventListener('mouseleave',()=>{if(!geoOpenContinent){hoverTimer=setTimeout(()=>{geoHoverContinent=null;const dd=wrap.querySelector('.geo-tab-dropdown');if(dd)dd.classList.remove('visible')},150)}});
bar.appendChild(tab)});
wrap.appendChild(bar);
const dd=document.createElement('div');dd.className='geo-tab-dropdown';
dd.addEventListener('mouseenter',()=>{if(hoverTimer)clearTimeout(hoverTimer)});
dd.addEventListener('mouseleave',()=>{if(!geoOpenContinent){hoverTimer=setTimeout(()=>{geoHoverContinent=null;dd.classList.remove('visible')},150)}});
wrap.appendChild(dd);
filterOptionsEl.appendChild(wrap);
if(geoOpenContinent)buildTabDropdown(wrap,cbc,geoOpenContinent,true)}}
function buildTabDropdown(wrap,cbc,cont,showList){
if(!cont)return;const dd=wrap.querySelector('.geo-tab-dropdown');if(!dd)return;
dd.innerHTML='';dd.classList.add('visible');
const countries=cbc[cont];const selCount=countries.filter(c=>filters.geo.has(c)).length;const allSel=countries.every(c=>filters.geo.has(c));
const acts=document.createElement('div');acts.className=showList?'geo-tab-actions':'geo-tab-hover-actions';
const hasUndo=continentUndo[cont]&&selCount===0;
if(selCount>0||hasUndo){const clrC=document.createElement('button');clrC.className='cat-clear visible';
if(hasUndo){clrC.textContent='↺';clrC.title='Undo clear';clrC.addEventListener('click',(ev)=>{ev.stopPropagation();continentUndo[cont].forEach(c=>filters.geo.add(c));delete continentUndo[cont];applyRebuild()})}
else{clrC.textContent='Clear';clrC.addEventListener('click',(ev)=>{ev.stopPropagation();continentUndo[cont]=countries.filter(c=>filters.geo.has(c));countries.forEach(c=>filters.geo.delete(c));applyRebuild();setTimeout(()=>{if(countries.some(c=>filters.geo.has(c))){delete continentUndo[cont];buildDesktop()}},5000)})}
acts.appendChild(clrC)}
const sa=document.createElement('button');sa.className='geo-sel-all'+(allSel?' all-selected':'');sa.textContent='Select all';sa.addEventListener('click',(ev)=>{ev.stopPropagation();if(allSel)countries.forEach(c=>filters.geo.delete(c));else countries.forEach(c=>filters.geo.add(c));applyRebuild()});acts.appendChild(sa);
dd.appendChild(acts);
if(showList){const list=document.createElement('div');list.className='geo-country-list';
countries.forEach(c=>{const item=document.createElement('div');item.className='geo-country-item'+(isolatedCountry&&c!==isolatedCountry?' grayed':'');
const cb=document.createElement('div');cb.className='geo-checkbox'+(filters.geo.has(c)?' checked':'');item.appendChild(cb);
const lbl=document.createElement('span');lbl.textContent=c;item.appendChild(lbl);
const radio=document.createElement('div');radio.className='geo-radio'+(isolatedCountry===c?' active':'');radio.title='';
let ht=null;
radio.addEventListener('mouseenter',()=>{ht=setTimeout(()=>{radio.title='Filter '+c+' only'},3000)});
radio.addEventListener('mouseleave',()=>{if(ht)clearTimeout(ht);radio.title=''});
radio.addEventListener('click',(ev)=>{ev.stopPropagation();if(isolatedCountry===c){fadingIsoCountry=c;isolatedCountry=null;radio.classList.add('fading');if(isoRadioTimer)clearTimeout(isoRadioTimer);if(fadingIsoTimer)clearTimeout(fadingIsoTimer);fadingIsoTimer=setTimeout(()=>{fadingIsoCountry=null;buildDesktop()},10000);isoRadioTimer=setTimeout(()=>{applyRebuild()},0)}else{isolatedCountry=c;fadingIsoCountry=null;if(fadingIsoTimer)clearTimeout(fadingIsoTimer)}applyRebuild()});
item.appendChild(radio);
item.addEventListener('click',()=>{if(filters.geo.has(c))filters.geo.delete(c);else filters.geo.add(c);applyRebuild()});
list.appendChild(item)});
dd.appendChild(list)}}
function applyRebuild(){const fl=getFiltered();map.getSource('clusters').setData(buildCluster(fl));map.getSource('pins').setData(buildPins(fl));hideOv();updateStats(fl);buildDesktop();updateMobileUI();
if(totalActive()>0&&lastFilters){if(undoTimer)clearTimeout(undoTimer);undoTimer=setTimeout(()=>{lastFilters=null;buildDesktop();updateMobileUI()},5000)}}
const mobileIcon=document.getElementById('mobileFilterIcon'),mobileBadge=document.getElementById('mobileIconBadge'),mobileClear=document.getElementById('mobileClearBtn'),overlay=document.getElementById('filterOverlay'),panelBody=document.getElementById('filterPanelBody'),footerStats=document.getElementById('filterFooterStats');
function buildMobile(){panelBody.innerHTML='';catDefs.forEach(cat=>{const sec=document.createElement('div');sec.className='mobile-cat-section';const hdr=document.createElement('div');hdr.className='mobile-cat-header';const lbl=document.createElement('div');lbl.className='mobile-cat-label';lbl.textContent=cat.label;hdr.appendChild(lbl);
const clrb=document.createElement('button');clrb.className='mobile-cat-clear'+(filters[cat.id].size>0?' visible':'');clrb.textContent='Clear';clrb.addEventListener('click',()=>{filters[cat.id].clear();applyRebuild();buildMobile()});hdr.appendChild(clrb);
sec.appendChild(hdr);
if(cat.id==='geo'){buildGeoMobile(sec);panelBody.appendChild(sec);return}
const od=document.createElement('div');od.className='mobile-cat-options';getOpts(cat.id).forEach(opt=>{const b=document.createElement('button');b.className='mobile-opt-btn'+(filters[cat.id].has(opt.id)?' active':'');if(cat.id==='sector'&&SC[opt.id])b.innerHTML=`<span class="opt-dot" style="background:${SC[opt.id]}"></span>${opt.label}`;else b.textContent=opt.label;b.addEventListener('click',()=>{if(filters[cat.id].has(opt.id))filters[cat.id].delete(opt.id);else filters[cat.id].add(opt.id);applyRebuild();buildMobile()});od.appendChild(b)});sec.appendChild(od);panelBody.appendChild(sec)});updateMobileFooterStats()}
function buildGeoMobile(sec){
const row=document.createElement('div');row.className='mobile-cat-options';row.style.marginBottom='8px';
const suggested=getSuggestedCountries();const vis=suggested.slice(0,8);
if(vis.length>0){const ivLabel=document.createElement('span');ivLabel.style.cssText='font-size:10px;color:var(--gt-muted);font-weight:500;margin-left:4px;white-space:nowrap';ivLabel.textContent='In view:';row.appendChild(ivLabel)}
vis.forEach(c=>{const pill=document.createElement('span');pill.className='geo-inview-pill'+(filters.geo.has(c)?' selected':'');pill.textContent=c;pill.addEventListener('click',()=>{if(filters.geo.has(c))filters.geo.delete(c);else filters.geo.add(c);applyRebuild();buildMobile()});row.appendChild(pill)});
if(suggested.length>8){const more=document.createElement('span');more.className='geo-more-btn';more.textContent=`+${suggested.length-8} more`;row.appendChild(more)}
sec.appendChild(row);
{const cbc=getCountriesByContinent();Object.keys(cbc).forEach(cont=>{const countries=cbc[cont];
const ch=document.createElement('div');ch.style.display='flex';ch.style.alignItems='center';ch.style.gap='6px';ch.style.margin='10px 0 6px';ch.style.cursor='pointer';
const cn=document.createElement('span');cn.style.cssText='font-size:11px;font-weight:600;color:var(--gt-muted);text-transform:none';cn.textContent=cont;
const isOpen=geoOpenContinent===cont;
const arrow=document.createElement('span');arrow.textContent=isOpen?'▾':'▸';arrow.style.fontSize='9px';arrow.style.color='var(--gt-muted)';
ch.appendChild(cn);ch.appendChild(arrow);
const selCount=countries.filter(c=>filters.geo.has(c)).length;
if(selCount>0){const cnt=document.createElement('span');cnt.style.cssText='font-size:9px;color:var(--gt-muted)';cnt.textContent=`(${selCount})`;ch.appendChild(cnt)}
const allSel=countries.every(c=>filters.geo.has(c));
const btnWrap=document.createElement('span');btnWrap.style.cssText='display:flex;gap:4px;margin-left:auto;align-items:center';
const hasUndo=continentUndo[cont]&&selCount===0;
if(selCount>0||hasUndo){const clrC=document.createElement('button');clrC.className='geo-sel-all';
if(hasUndo){clrC.textContent='↺';clrC.addEventListener('click',(ev)=>{ev.stopPropagation();continentUndo[cont].forEach(c=>filters.geo.add(c));delete continentUndo[cont];applyRebuild();buildMobile()})}
else{clrC.textContent='Clear';clrC.addEventListener('click',(ev)=>{ev.stopPropagation();continentUndo[cont]=countries.filter(c=>filters.geo.has(c));countries.forEach(c=>filters.geo.delete(c));applyRebuild();buildMobile();setTimeout(()=>{if(countries.some(c=>filters.geo.has(c))){delete continentUndo[cont];buildMobile()}},5000)})}
btnWrap.appendChild(clrC)}
const sa=document.createElement('button');sa.className='geo-sel-all'+(allSel?' all-selected':'');sa.textContent='Select all';sa.addEventListener('click',(ev)=>{ev.stopPropagation();if(allSel)countries.forEach(c=>filters.geo.delete(c));else countries.forEach(c=>filters.geo.add(c));applyRebuild();buildMobile()});btnWrap.appendChild(sa);
ch.appendChild(btnWrap);
ch.addEventListener('click',()=>{geoOpenContinent=isOpen?null:cont;buildMobile()});
sec.appendChild(ch);
if(isOpen){const list=document.createElement('div');list.style.cssText='max-height:240px;overflow-y:auto;padding:2px 0 2px 4px';
countries.forEach(c=>{const item=document.createElement('div');item.className='geo-country-item';
const cb=document.createElement('div');cb.className='geo-checkbox'+(filters.geo.has(c)?' checked':'');item.appendChild(cb);
const lbl=document.createElement('span');lbl.textContent=c;item.appendChild(lbl);
item.addEventListener('click',()=>{if(filters.geo.has(c))filters.geo.delete(c);else filters.geo.add(c);applyRebuild();buildMobile()});
list.appendChild(item)});
sec.appendChild(list)}})}}
function updateMobileFooterStats(){const fl=getFiltered();const tc=fl.reduce((s,d)=>s+(d.amount||0),0);footerStats.innerHTML=`<span class="filter-footer-stat"><strong>${fl.length}</strong> deals</span><span class="filter-footer-stat"><strong>${fmt(tc)}</strong> capital</span>`;
const clrBtn=document.getElementById('filterFooterClear');
if(totalActive()>0){clrBtn.className='filter-footer-clear visible';clrBtn.textContent='Clear all filters'}else if(lastFilters){clrBtn.className='filter-footer-clear visible';clrBtn.textContent='Reapply last filters'}else{clrBtn.className='filter-footer-clear'}}
function updateMobileUI(){const ta=totalActive();mobileBadge.style.display=ta>0?'block':'none';mobileBadge.textContent=ta;mobileClear.style.display=ta>0?'block':'none'}
function openMobilePanel(){overlay.style.display='block';buildMobile()}
function closeMobilePanel(){overlay.style.display='none';applyRebuild()}
mobileIcon.addEventListener('click',openMobilePanel);
document.getElementById('filterPanelClose').addEventListener('click',closeMobilePanel);
overlay.addEventListener('click',e=>{if(e.target===overlay)closeMobilePanel()});
document.getElementById('filterFooterClear').addEventListener('click',()=>{if(lastFilters&&totalActive()===0){restoreFiltersSnapshot(lastFilters);lastFilters=null}else{clearAll()}applyRebuild();buildMobile()});
mobileClear.addEventListener('click',()=>{clearAll();applyRebuild()});
const ZT=9,CZT=6;
const initCenter=window.innerWidth<=640?[-65,15]:[-40,15];
const map=new mapboxgl.Map({container:'map',style:'mapbox://styles/mapbox/light-v11',center:initCenter,zoom:2.5,minZoom:2,maxZoom:16,attributionControl:false});
map.addControl(new mapboxgl.AttributionControl({compact:true}),'bottom-right');
let spinning=true;let lastSpin=0;
function spinGlobe(ts){if(!spinning)return;if(ts-lastSpin>50){const center=map.getCenter();map.setCenter([center.lng-0.06,center.lat],{duration:0});lastSpin=ts}requestAnimationFrame(spinGlobe)}
requestAnimationFrame(spinGlobe);
['mousedown','touchstart','wheel','dblclick'].forEach(ev=>map.getCanvas().addEventListener(ev,()=>{spinning=false},{once:true}));
map.on('dragstart',()=>{spinning=false});
map.on('zoomstart',()=>{spinning=false});
map.on('load',()=>{
try{const gtNames=Object.keys(COUNTRY_DATA);if(map.getLayer('country-label'))map.setFilter('country-label',['!',['match',['get','name_en'],gtNames,true,false]])}catch(e){}
map.addSource('clusters',{type:'geojson',data:buildCluster(deals)});
map.addSource('pins',{type:'geojson',data:buildPins(deals)});
map.addSource('gt-country-labels',{type:'geojson',data:{type:'FeatureCollection',features:Object.entries(COUNTRY_DATA).map(([name,d])=>({type:'Feature',geometry:{type:'Point',coordinates:d.labelCoords},properties:{name:name}}))}});
map.addLayer({id:'city-clusters',type:'circle',source:'clusters',filter:['==',['get','isCluster'],true],paint:{'circle-radius':['interpolate',['linear'],['get','dealCount'],1,16,5,24,10,32,20,40],'circle-color':'#1B4332','circle-opacity':.88,'circle-stroke-width':3,'circle-stroke-color':'#fff','circle-stroke-opacity':.9}});
map.addLayer({id:'city-cluster-count',type:'symbol',source:'clusters',filter:['==',['get','isCluster'],true],layout:{'text-field':['get','dealCount'],'text-font':['DIN Pro Bold','Arial Unicode MS Bold'],'text-size':15,'text-allow-overlap':true},paint:{'text-color':'#fff'}});
map.addLayer({id:'city-cluster-name',type:'symbol',source:'clusters',filter:['==',['get','isCluster'],true],layout:{'text-field':['get','city'],'text-font':['DIN Pro Medium','Arial Unicode MS Regular'],'text-size':12,'text-offset':[0,3],'text-anchor':'top'},paint:{'text-color':'#1B4332','text-halo-color':'#fff','text-halo-width':2}});
map.addLayer({id:'single-pins',type:'circle',source:'clusters',filter:['==',['get','isCluster'],false],paint:{'circle-radius':10,'circle-color':['coalesce',['get','color'],'#9CA3AF'],'circle-opacity':.88,'circle-stroke-width':2,'circle-stroke-color':'#fff'}});
map.addLayer({id:'single-pin-name',type:'symbol',source:'clusters',filter:['==',['get','isCluster'],false],layout:{'text-field':['get','city'],'text-font':['DIN Pro Medium','Arial Unicode MS Regular'],'text-size':11,'text-offset':[0,2],'text-anchor':'top'},paint:{'text-color':'#555','text-halo-color':'#fff','text-halo-width':1.5}});
map.addLayer({id:'gt-country-label',type:'symbol',source:'gt-country-labels',maxzoom:CZT,layout:{'text-field':['get','name'],'text-font':['DIN Pro Bold','Arial Unicode MS Bold'],'text-size':16,'text-allow-overlap':true},paint:{'text-color':'#4B7FA8','text-halo-color':'rgba(75,127,168,0.25)','text-halo-width':1.5}});
map.addLayer({id:'deal-pins',type:'circle',source:'pins',minzoom:ZT,paint:{'circle-radius':['get','radius'],'circle-color':['get','color'],'circle-opacity':.88,'circle-stroke-width':2,'circle-stroke-color':'#fff'}});
map.addLayer({id:'deal-labels',type:'symbol',source:'pins',minzoom:ZT,filter:['has','amount'],layout:{'text-field':['get','amountFormatted'],'text-font':['DIN Pro Medium','Arial Unicode MS Regular'],'text-size':10,'text-offset':[0,-2],'text-anchor':'bottom','text-allow-overlap':false},paint:{'text-color':'#1a1a1a','text-halo-color':'#fff','text-halo-width':1.5}});
map.on('zoom',()=>{const z=map.getZoom();const v=z<ZT;['city-clusters','single-pins'].forEach(l=>{map.setPaintProperty(l,'circle-opacity',v?.88:0);map.setPaintProperty(l,'circle-stroke-opacity',v?.9:0)});['city-cluster-count','city-cluster-name','single-pin-name'].forEach(l=>map.setPaintProperty(l,'text-opacity',v?1:0));document.getElementById('backBtn').style.display=z>=CZT+0.5?'block':'none';if(z>=ZT)hideOv()});
map.on('moveend',()=>{if(openCategory==='geo'&&!spinning)buildDesktop()});
map.on('click','city-clusters',e=>{if(map.getZoom()<ZT){const city=e.features[0].properties.city;if(COUNTRY_DATA[getCountryForCity(city)]&&!CITIES[city])showOv('country',getCountryForCity(city));else showOv('city',city)}});
map.on('click','single-pins',e=>{if(map.getZoom()<ZT){const p=e.features[0].properties;const country=p.country||getCountryForCity(p.city);if(country==='Singapore')showOv('country','Singapore');else showDeal(e.features[0])}});
map.on('click','deal-pins',e=>{hideOv();showDeal(e.features[0])});
map.on('click','gt-country-label',e=>{const name=e.features[0].properties.name;if(COUNTRY_DATA[name])showOv('country',name)});
['city-clusters','single-pins','deal-pins','gt-country-label'].forEach(l=>{map.on('mouseenter',l,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',l,()=>map.getCanvas().style.cursor='')});
buildDesktop();updateMobileUI();updateStats(deals)});
function getCountryForCity(city){const d=deals.find(x=>x.city===city);return d?d.country:''}
document.getElementById('backBtn').addEventListener('click',()=>{const cd=COUNTRY_DATA[lastCountry];if(cd&&cd.zoomTo)map.flyTo({...cd.zoomTo,duration:1000});else map.flyTo({center:[-40,15],zoom:2.5,duration:1000});hideOv()});
function showOv(level,name){const card=document.getElementById('overviewCard');let data,dl;
if(level==='country'){data=COUNTRY_DATA[name];dl=getFiltered().filter(d=>d.country===name);lastCountry=name;document.getElementById('backBtn').textContent='← View '+name}else{data=CITIES[name];dl=(cityGroups[name]||[]).filter(matchFilter);const cc=getCountryForCity(name);if(cc&&COUNTRY_DATA[cc]){lastCountry=cc;document.getElementById('backBtn').textContent='← View '+cc}}
if(!data)return;const tc=dl.reduce((s,d)=>s+(d.amount||0),0);
document.getElementById('ovTitle').textContent=level==='country'?name:`${name}, ${data.state}`;
document.getElementById('ovDeals').textContent=dl.length;
document.getElementById('ovCapital').textContent=fmt(tc);
document.getElementById('ovBlurb').textContent=data.blurb;
document.getElementById('ovSidebar').textContent=data.sidebar;
const fr=document.getElementById('ovFilterRow');const fc=document.getElementById('ovFilterCheck');const fl=document.getElementById('ovFilterLabel');
if(level==='country'){fr.style.display='flex';fc.className='ov-filter-check'+(isolatedCountry===name?' checked':'');fl.textContent='Filter '+name+' only';fr.onclick=()=>{if(isolatedCountry===name){fadingIsoCountry=name;isolatedCountry=null;if(isoRadioTimer)clearTimeout(isoRadioTimer);if(fadingIsoTimer)clearTimeout(fadingIsoTimer);fadingIsoTimer=setTimeout(()=>{fadingIsoCountry=null;buildDesktop()},10000)}else{isolatedCountry=name;fadingIsoCountry=null;if(fadingIsoTimer)clearTimeout(fadingIsoTimer)}applyRebuild();showOv(level,name)}}else{fr.style.display='none'}
const zb=document.getElementById('ovZoomBtn');zb.textContent=level==='country'?'View':'Zoom in';zb.onclick=()=>{if(level==='country')map.flyTo({...data.zoomTo,duration:1200});else map.flyTo({center:data.coords,zoom:11,duration:1200});hideOv()};
card.style.visibility='hidden';card.style.display='block';const cw=map.getContainer().clientWidth;const ch=map.getContainer().clientHeight;const cardW=Math.min(400,cw-40);const cardH=card.offsetHeight;card.style.left=((cw-cardW)/2)+'px';card.style.right='auto';card.style.transform='none';card.style.bottom='auto';
if(level==='country'){card.style.top=Math.max(20,(ch-cardH)/2)+'px'}else{const pt=map.project(data.coords);if(pt.y<ch/3){card.style.top=Math.max(pt.y+30,130)+'px'}else if(pt.y>ch*2/3){card.style.top=Math.max(20,pt.y-cardH-30)+'px'}else{card.style.top=Math.max(20,pt.y-cardH/2)+'px'}}card.style.visibility='visible'}
function hideOv(){document.getElementById('overviewCard').style.display='none'}
document.getElementById('ovClose').addEventListener('click',hideOv);
function getSmartAnchor(ll){const pt=map.project(ll);const w=map.getContainer().clientWidth;const h=map.getContainer().clientHeight;const mb=isMobile();const pw=mb?135:160;const ph=mb?200:260;const topZone=mb?130:170;let vert='bottom';if(pt.y<ph+topZone)vert='top';let horiz='';if(w-pt.x<pw+15)horiz='right';else if(pt.x<pw+15)horiz='left';if(mb&&pt.x<70&&pt.y<140){vert='top';horiz='left'}return horiz?vert+'-'+horiz:vert}
function showDeal(f){const p=f.properties;const c=p.color||SC[p.sector]||'#9CA3AF';const sl=p.sectorLabel||SL[p.sector]||p.sector;const anchor=getSmartAnchor(f.geometry.coordinates);const mb=isMobile();
const loc=p.state?`${p.city}, ${p.state}, ${p.country}`:`${p.city}, ${p.country}`;
const popup=new mapboxgl.Popup({offset:15,maxWidth:mb?'270px':'320px',anchor:anchor}).setLngLat(f.geometry.coordinates).setHTML(`<div class="popup-header"><div class="popup-deal-type">${p.dealType}</div><div class="popup-title">${p.investor} → ${p.recipient}</div></div><div class="popup-body"><div class="popup-row"><span class="popup-label">Amount (USD)</span><span class="popup-value">${p.amountFormatted||fmt(p.amount)}</span></div><div class="popup-row"><span class="popup-label">Sector</span><span class="popup-value"><span class="popup-sector-tag" style="background:${c}22;color:${c}">${sl}</span></span></div><div class="popup-row"><span class="popup-label">Location</span><span class="popup-value">${loc}</span></div><div class="popup-row"><span class="popup-label">Date</span><span class="popup-value">${p.date}</span></div><div class="popup-row"><span class="popup-label">Source</span><span class="popup-value">${p.source}</span></div><div class="popup-notes">${p.notes}</div></div>`).addTo(map);
if(mb){setTimeout(()=>{const el=popup.getElement();if(!el)return;const r=el.getBoundingClientRect();const cr=map.getContainer().getBoundingClientRect();let px=0,py=0;if(r.left<cr.left+8)px=r.left-cr.left-8;if(r.right>cr.right-8)px=r.right-cr.right+8;if(r.top<cr.top+8)py=r.top-cr.top-8;if(r.bottom>cr.bottom-8)py=r.bottom-cr.bottom+8;if(px!==0||py!==0)map.panBy([px,py],{duration:300})},50)}}
function updateStats(dl){const tc=dl.reduce((s,d)=>s+(d.amount||0),0);document.getElementById('stats').innerHTML=`<div class="stat-card"><div class="stat-value">${dl.length}</div><div class="stat-label">Deals tracked</div></div><div class="stat-card"><div class="stat-value" style="display:flex;justify-content:space-between;align-items:baseline;gap:8px">${fmt(tc)}<span style="font-family:'DM Sans',sans-serif;font-size:10px;color:var(--gt-muted);font-weight:600;letter-spacing:.04em">USD</span></div><div class="stat-label">Capital identified</div></div>`}
